# Generated by Django 4.2.7 on 2024-01-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyphonenumber',
            name='otp_for',
            field=models.CharField(choices=[('N', 'New Account'), ('A', 'Auth Login/Register')], max_length=1),
        ),
    ]
